### ISSUE TITLE
Double-indent on new scope without a preceding token on the same line

### ISSUE THREAD

**Issue by AdamNiederer** [orzechowskid/tsi.el#20]
All cases shown with tsi-typescript-indent-offset = 2; it will indent 8 spaces for tsi-typescript-indent-offset = 4, etc.

Reproduction:

```js
{
    0
}
```

Expected:
```js
{
  0
}
```

Cases that also don't work:

```js
{
    0
    0
}
```

```js
0
{
    0
}
```

```js
if(0)
{
    0
}
```

Cases that do work:

```js
0 {
  0
}
```

**Comment by stevemolitor** [comment]
Fixed by d25c54e6966d7a5fc83663f85e06eaaba74d7244 in #20.
