### ISSUE TITLE
Blank lines below switch cases with scopes are double-indented

### ISSUE THREAD

**Issue by AdamNiederer** [orzechowskid/tsi.el#22]
All cases tested with tsi-typescript-indent-offset = 2

Given this case:

```js
switch(0) {
  case 0: {
      
  }
}
```

Moving the cursor to the third (blank) line and indenting yields a double-indent, like so (`|` representing the cursor):

```js
switch(0) {
  case 0: {
      |
  }
}
```

When that third line is not blank, it will indent to the correct level (in this case 6)
```js
switch(0) {
  case 0: {
    0
  }
}
```

However, when entering another line, the next line will also be over-indented (`|` representing the cursor):

```js
switch(0) {
  case 0: {
    0
      |
  }
}
```

**Comment by stevemolitor** [comment]
This is fixed by #18.

**Comment by orzechowskid** [comment]
#18 was just merged; please tell `straight.el` to re-fetch your copy of this repo and let us know how it goes.

**Comment by AdamNiederer** [comment]
This one also works; thanks!
