### ISSUE TITLE
add support for [S]CSS

### ISSUE THREAD

**Issue by orzechowskid** [orzechowskid/tsi.el#6]
this would be extremely useful by itself, but also as the basis for CSS-in-JS indentation someday

**Comment by orzechowskid** [comment]
#12

**Comment by stevemolitor** [comment]
> as the basis for CSS-in-JS indentation someday

I would like that, and CSS-in-JS syntax highlighting. How would one go about that? Via [tree sitter language injection queries](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection)? Or a new grammar, combining ts / tsx / css?

**Comment by orzechowskid** [comment]
I don't yet know enough about building tree-sitter queries to make it happen, but I agree that language injection seems like the tool for the job.  conceptually, indentation of CSS-in-JS seems simple: figure out which tree nodes are of type `template_string`, indent them using tsi-typescript as if they were regular strings, then parse the string as CSS and apply extra indentation via tsi-css.

in the meantime, I've been working on https://github.com/orzechowskid/tsx-mode.el lately which builds on top of this library plus a few others to provide indentation and syntax-highlighting for CSS-in-JS in a different way.

**Comment by stevemolitor** [comment]
> in the meantime, I've been working on https://github.com/orzechowskid/tsx-mode.el 

Very cool I'm using it now!
