### ISSUE TITLE
Indent TSX / JSX attributes when starting new line

### ISSUE THREAD

**Issue by stevemolitor** [orzechowskid/tsi.el#8]
`tsi.el` does not handle indenting new lines inside a JSX opening or self-closing tag well. 

## Current Behavior

Here is what it looks like current when adding a new line inside a JSX opening or self-closing tag:

![before](https://user-images.githubusercontent.com/219235/154813828-3c97c44c-530a-4eed-ab0f-dcc93129fd5b.gif)

Note that `C-j` will not indent as expected. After typing the attribute, you can then press TAB to indent, but that's a little annoying.

## Desired Behavior

I'd like to get the indentation right away, after typing ie `C-j`:

![after](https://user-images.githubusercontent.com/219235/154813798-b4d6630d-2994-4e46-8c15-b884a8430ac1.gif)

The indentation of attributes is now the same as how `prettier` indents with its default settings.

## Hacky PR

I have a hacky PR here that implements the desired behavior: #7.

It's hacky though - see notes in PR. I'd appreciate some advice on a better solution.

## Related Issues

A similar thing happens with new lines after opening parenthesis in some cases:

```ts
function Component () {
  return ( // type C-j here
  );
}
```  

The cursor will line up right under the opening `(` after typing `C-j`. I'd like it to indent ie 2 spaces to the right. 

I have a hacky fix for this also! I didn't include that in my PR. No point in adding onto the hack!

## Thanks

Great package btw. I thoroughly enjoying it. Super snappy and fast, and it gets me away from `web-mode` - I can just use `typescript-mode` (and lsp-mode if desired) now. The code is clear also.

**Comment by orzechowskid** [comment]
we also need to think about the self-closing element case:
```
<div |/>
     ^---- point is here
```
```
<div
|/>
^---- point is now here
```
and the other case from your report, where attributes are already present:
```
<div|
    ^---- point is here
  data-foo="foo" />
```
```
<div
|
^---- point is now here
  data-foo="foo"/>
```

**Comment by stevemolitor** [comment]
Thanks for the clear response.

I was wrong about prettier and `>` - when there are many attributes it indents the `>` in a JSX opening tag on the same column as the opening `<`:

```tsx
 <div
  x={1}
  y={2}
  {/* ... more attributes ... */}
>
```

When there are few attributes prettier puts it all one one line - `<div x={1}>`. 

So I think the way `tsi.el` works currently regarding `>` on a single line is correct.

I do think the case where attributes are already present is worth adjusting:

```tsx
<div|
    ^---- point is here
  data-foo="foo" 
/>
```

I think that's a common scenario, where you want to add an attribute at the top or bottom of the attributes list, and expect `tsi.el` to ident to align with the other attributes. Fwiw `web-mode` indents the way I would expect here (but `tsi.el` does not). 

It's a similar situation with parenthesis:

```ts
if (
  x === 1 &&
  y === 2 &&|
                  ^ point is here
)
```

I would expect it to indent to align with the other conditions, but it does not. Vanilla `typescript-mode` and `web-mode` will indent to align with the other conditions, but `tsi.el` does not.

It's tricky to implement however in `tsi-typescript.el` however. When the point is on a blank line inside a JSX opening or self closing element, `tsc-node-text` will return the entire node text:

```elisp
"<div
    x={1}
    
>"

If you check to see if the current line is blank in your condition, it breaks when there are nested JSX elements. As `tsi-walk` walks the tree it adds, 2, then 4, then 6 etc spaces for level. So I resorted to adding some code inside `tsi-walk`, just _after_ the tree walking finishes, to give me a chance to add a little extra indentation for the current line only. The problem with that of course is that I put typescript specific code inside the generic `tsi.el` file. One solution would be to add a second optional function arg to `tsi-walk`, to plug in special cases. Ie:

```elisp
(defun tsi-typescript--indent-line ()
  (tsi-walk #'tsi-typescript--get-indent-for #'tsi-typescript--get-extra-indent-for-current-line))
```

Not ideal, but not completely horrible either.

🤔

**Comment by stevemolitor** [comment]
Another solution would be to make `tsi-walk` side-effect free, so that it only computes the indent but does not actually indent the line. That would allow more options to adjust its behavior: 

```elisp
;; not tested

(defun tsi-typescript--indent-line ()
  (let* ((indent (or (tsi-walk #'tsi-typescript--get-indent-for) 0))
         (extra-indent (tsi-typescript--get-indent-for-currentline))
         (column (+ indent extra-indent)))
    (tsi-indent-line-to column)))

(defun tsi-indent-line-to (column)
  (let* ((should-save-excursion (< first-non-blank-pos (point))))
    (if should-save-excursion
        (save-excursion
          (indent-line-to column))
      (indent-line-to column))))
```

Part of the challenge here is that `tsi-walk` both computes the final indentation _and_ performs the side effect of indenting the line. Separating the two would provide more flexibility.

Happy to spin up PR along one of these lines.

**Comment by orzechowskid** [comment]
oh, I think splitting the calculation and the application is a great idea.  would love to see a PR for that if you're still up for it.

**Comment by stevemolitor** [comment]
> oh, I think splitting the calculation and the application is a great idea. would love to see a PR for that if you're still up for it.

Cool will do - give me a day or two.

**Comment by stevemolitor** [comment]
OK here's the PR: #9.
